### ISSUE TITLE
Preparation for IETF 116

### ISSUE THREAD

**Issue by BasilGuo** [bemasc/risav#41]
As we have requested agenda from `ipsecme`, `6man`, and `secdispatch`, I will make slides for each one. Hope I can complete it this week.

**Comment by BasilGuo** [comment]
Now we have gotten a reply from `secdispatch`. I don't know whether you received it as I send this to your  <bemasc@google.com>. Following is the reply message from the chair,

> We have one hour allocated for the SecDispatch session, and we already have 4 topics to discuss.
> Your topic would be the 5th, and it is unlikely that we would have enough time to cover all 5 topics.
> We will try to get to it, if one of the other topics gets dropped.

**Comment by bemasc** [comment]
Thanks for volunteering to prepare slides.

Going forward, "ietf@bemasc.net" is my preferred address for IETF-related communication.

**Comment by BasilGuo** [comment]
The full version slide of RISAV is ready for IETF 116.
Feel free to view, comment, and edit it with the following link.
I will reduce it based on time limits if we could make a presentation at the `secdispatch`.

[[ipsecme] IETF 116 - An RPKI and IPsec-based AS-to-AS Approach for Source Address Validation](https://docs.google.com/presentation/d/1fY7dcYIt118K2mpz5R_jbwDCoIA3aKfWjCCqxo8-kTc/edit?usp=sharing)
