### ISSUE TITLE
New version for SIDRops?

### ISSUE THREAD

**Issue by BasilGuo** [bemasc/risav#54]
Russ Housley, one of the chairs of SIDRops, asks us to share RISAV at SIDRops when it is ready.

I think it is time for us to share with them at this meeting.

Shall we publish a new version 02 as we have amended the ASN.1 of the RISAVAnnouncement?
Or do we still use version 01?

**Comment by bemasc** [comment]
I think we might as well publish a new version before the draft cutoff.

**Comment by BasilGuo** [comment]
I'm sorry. After trying 2 times, it still uploads the old one.
But the Editor's Copy has the right version. And so does it in the tag `draft-xu-ipsecme-risav-02`.
Commit id:  d71c928 is the latest one indeed.
So, instead, I will upload it by hand.

![image](https://github.com/bemasc/risav/assets/42705918/3e84c74e-2b02-4603-ae93-6a224d92d05e)

![image](https://github.com/bemasc/risav/assets/42705918/89ab0ec0-19f1-4ba2-9851-6da13b222108)

![image](https://github.com/bemasc/risav/assets/42705918/6356ca1c-8382-434f-b54a-9b9158eb6688)

**Comment by BasilGuo** [comment]
Well, maybe this is because of the cache of the website.

Here is the [link](https://datatracker.ietf.org/submit/status/134673/93a757b2c433b40d658cd13edfc7689b/) though I don't post it now.

Open the [XML](https://www.ietf.org/staging/draft-xu-ipsecme-risav-02.xml) format and change the suffix to `.html` or `.txt.

The [HTML](https://www.ietf.org/staging/draft-xu-ipsecme-risav-02.html) format is still the old one when I upload it by hand.
But the [TXT](https://www.ietf.org/staging/draft-xu-ipsecme-risav-02.txt) format is the newest one.

**So, is it right to go on uploading it in this case?**

![image](https://github.com/bemasc/risav/assets/42705918/7a7cab9c-992d-41be-afdb-aeed1ab1a543)

**Comment by BasilGuo** [comment]
The matter has been properly resolved. The content is correct now. This may be because of the cache of the website.
