### ISSUE TITLE
Tunnel mode AEAD adjustment proposal

### ISSUE THREAD

**Issue by bemasc** [bemasc/risav#56]
@BasilGuo proposes the following AEAD adjustment

> Traditionally, the ESP ICV is computed on the entire ESP packet, excluding the Authentication Data field. Here, in RISAV, the ESP ICV SHOULD be calculated including the IP Source Address at first, following by SPI, Sequence Number, Payload Data, Padding (if present), Pad Length, and Next Header. Destination Address is ignored.

**Comment by bemasc** [comment]
I don't understand the motivation for this change.  Why not authenticate the destination address?  Each deviation from standard IPsec makes RISAV harder to implement, so I would like to stick to standard IPsec processing when possible.

**Comment by BasilGuo** [comment]
Thanks. I should write more clearly. Here IP source/destination address is the outter one, not the inner one. The Payload Data includes the inner IP address.
You're right. The process should not make such a adjustment. Keep it simple as the standard IPsec.

**Comment by bemasc** [comment]
OK, we can revisit this idea if it becomes necessary.
